image: node:16.13.1

stages:
  - deploy

cache:
  paths:
    - app/node_modules/

before_script:
  - apt-get update -qq && apt-get install -y -qq sshpass rsync

prod1:
  stage: deploy
  only:
    refs:
      - main
  environment: Production
  script:
    - cd app
    - yarn
    - yarn install
    - CI=false yarn run build
    - cd build
    - ls
    - sshpass -V
    - export SSHPASS=$SERVERPASS
    - sshpass -e rsync -r --omit-dir-times -e "ssh -o StrictHostKeyChecking=no" . netiq@23.227.167.67:/var/www/netiq/app
